### PR TITLE
add .gitignore files in fpga build folders

### PR DESCRIPTION
**Pull request by Basseuph**
During the FPGA design build process a lot of temporary files are generated in the respective fpga project folders.

Let's add local _.gitignore_ files within these directories that hide these files, especially using `git gui` is otherwise almost impossible.

The alternative approach would be a 'global' _.gitignore_ file, e.g. located in the _fpga/mqnic/_ directory. However, this might be less straight-forward in case a single fpga build requires additional files to be visible.

Also the _.tox_ directory in the root of the repo directory structure is now hidden via the top level _.gitignore_ file.

### CODE REVIEW

**Comment by alexforencich** [comment]
I think avoiding gitignore files for each subdirectory would be better.  It looks like you can prefix lines with ! to exclude files from being ignored, and it seems like this is doable from within subdirectories.

**Comment by alexforencich** [comment]
Also, I totally forgot that yizhou had a PR for updating the gitignore files as well, I'll merge that one in first

**Comment by Basseuph** [comment]
OK, no wories, I'll look at what has / will be the situation post the previous merge.
You could even just pick the second commit w.r.t. tox, if applicable and the I'll revisit this topic at some point later

**Comment by Basseuph** [comment]
I'll close this as nothing happened for a long time and things advanced quite a bit.

**Pull request closed without merging**
