### PR TITLE
Add FPGA design, Linux platform driver and PetaLinux project to run on a ZCU106 board with PS as host system

### PR DESCRIPTION
**Pull request by joft-mle**
This is supposed to provide an initial solution to solve issue #57 and has also been discussed in Corundum Developer Meeting 2022/03/28.

The 1st commit adds the FPGA design, derived from the existing fpga_pcie design folder. The following 6 commits adjust various aspects to regarding the PS being used as the host system. The 7th commit particularly fixes an issue with bogus burst length reporting of the Xilinx PS block. This has been left as a separate commit to document the very unfortunate behavior.

The 7 commits regarding the FPGA are followed by 3 commits preparing and adding Linux platform driver support to the existing mqnic driver. Also, a PetaLinux/Yocto-Layer is added, including a Yocto recipe for building the mqnic driver.

This is followed by adding [psmake](https://github.com/missinglinkelectronics/psmake) as a subtree in squashed fashion. psmake is a set of convenience Makefiles for developing software targeting the embedded processors of SoC FPGAs. In this case the [PetaLinux part](https://github.com/missinglinkelectronics/psmake/blob/master/petalinux.mk) of it will be used.

The last 5 commits finally add a PetaLinux project. The purpose is to provide bootable images which include the mqnic driver and various typical networking utilities.

### CODE REVIEW

**Comment by alexforencich** [comment]
Excellent!

It looks like I missed pulling out that event queue parameter all the way to the top; I'll go ahead and feed that one through in all relevant modules so everything is consistent, and then those couple of commits can be removed from this PR.  

For the max burst length, now that we have the interleaving fixed (or, at least worked around), did you verify that the burst length does, in fact, have to be overridden to 16?

Also, as per previous discussions, have you checked to see if the SFP+ module communication works if the board is initially booted up without the module installed?

From looking at the build instructions, I'm wondering if something can be simplified a abit:

	cd ps/petalinux/
	make HDF=../../fpga/fpga.xsa gethdf
	make
	make package-boot

Main thing I think is it would be nice to have the default value of HDF specified somewhere so it doesn't need to be specified manually when building.  I can potentially see the point of not running gethdf on every build, but would it make sense to do that automatically on a clean build when running `make`?

**Comment by joft-mle** [comment]
> Excellent!
> 
> It looks like I missed pulling out that event queue parameter all the way to the top; I'll go ahead and feed that one through in all relevant modules so everything is consistent, and then those couple of commits can be removed from this PR.

ACK

> 
> For the max burst length, now that we have the interleaving fixed (or, at least worked around), did you verify that the burst length does, in fact, have to be overridden to 16?

We did not check again. However I don't expect that the situation has changed, since the query happens before Vivado looks at the source code. Honestly I don't really understand why fixing the interleaving should fix Vivado regarding its burst length reporting.

So I fear, I do not get your point here. :-(

> 
> Also, as per previous discussions, have you checked to see if the SFP+ module communication works if the board is initially booted up without the module installed?

No, not yet. The current assumption is, that the behavior is like in the PCIe designs.

> 
> From looking at the build instructions, I'm wondering if something can be simplified a abit:
> 
> ```
> cd ps/petalinux/
> make HDF=../../fpga/fpga.xsa gethdf
> make
> make package-boot
> ```
> 
> Main thing I think is it would be nice to have the default value of HDF specified somewhere so it doesn't need to be specified manually when building. I can potentially see the point of not running gethdf on every build, but would it make sense to do that automatically on a clean build when running `make`?

Yes, simplification is indeed possible here; I'll come up with a conveniences make target via psmake's local.mk feature.

Do you think this should also be integrated into the `fpga_zynqmp/Makefile`? So that running `make` there, also builds the PetaLinux project?

**Comment by alexforencich** [comment]
The point is I'm not sure if it's necessary to restrict the burst length to 16.  IIRC it seemed like that change made no difference.  If Vivado reports it as 256, and Vivado configures its own AXI components based off of that value, then maybe it's the Xilinx documentation that's wrong about the burst length being restricted to 16.  Perhaps they have logic to split up the bursts internally when converting to AXI3.

IMO, let's keep the PS and PL builds separate.  I can definitely see the use case for building the PS separately from the PL.  But, what we could do is set up that higher-level makefile to build both.

**Comment by alexforencich** [comment]
Also, was there a change included in this patch set for https://github.com/corundum/corundum/issues/89?  I just updated the default value of the KEEP_WIDTH parameters on the FIFOs, which should presumably fix that issue.

**Comment by joft-mle** [comment]
> Also, was there a change included in this patch set for #89? I just updated the default value of the KEEP_WIDTH parameters on the FIFOs, which should presumably fix that issue.

Not that I'm aware of. It's more like that the next step could be to add a system level testbench for this new `ZCU106/fpga_zynqmp` design.

**Comment by joft-mle** [comment]
> The point is I'm not sure if it's necessary to restrict the burst length to 16. IIRC it seemed like that change made no difference. If Vivado reports it as 256, and Vivado configures its own AXI components based off of that value, then maybe it's the Xilinx documentation that's wrong about the burst length being restricted to 16. Perhaps they have logic to split up the bursts internally when converting to AXI3.

Ok, understood. Well then, we first have to check in detail, whether having it set automatically breaks things or not. I'd say keeping it set manually for now puts us on the safe side, no matter what is actually the case. I'll put such an experiment on our TODO list then ...

**Comment by joft-mle** [comment]
> > Also, as per previous discussions, have you checked to see if the SFP+ module communication works if the board is initially booted up without the module installed?
> 
> No, not yet. The current assumption is, that the behavior is like in the PCIe designs.

Yesterday, we conducted a quick experiment regarding booting without one of the 2 SFP modules plugged **in relation to module EEPROM dumping only** - result:

- It does not matter whether the SFP module is plugged in during boot or not.
- When a SFP module is not plugged in, the eeprom driver is still applied to the device tree nodes created via `system-user.dtsi`, as I suspected previously. I2C-related kernel messages clearly report the 2 SFP module EEPROM instances, even if the second one (bus 21, address 51, for ZCU106 SFP1) is not there in this case:

```
[    4.198635] pca953x 0-0020: supply vcc not found, using dummy regulator
[    4.205324] pca953x 0-0020: using no AI
[    4.209870] pca953x 0-0021: supply vcc not found, using dummy regulator
[    4.216539] pca953x 0-0021: using no AI
[    4.229885] i2c i2c-0: Added multiplexed i2c bus 2
[    4.241403] i2c i2c-0: Added multiplexed i2c bus 3
[    4.257238] random: fast init done
[    4.299523] i2c i2c-0: Added multiplexed i2c bus 4
[    4.304432] i2c i2c-0: Added multiplexed i2c bus 5
[    4.309220] pca954x 0-0075: registered 4 multiplexed busses for I2C mux pca9544
[    4.316553] cdns-i2c ff020000.i2c: 400 kHz mmio ff020000 irq 39
[    4.324185] at24 6-0054: supply vcc not found, using dummy regulator
[    4.331065] at24 6-0054: 1024 byte 24c08 EEPROM, writable, 1 bytes/write
[    4.337801] i2c i2c-1: Added multiplexed i2c bus 6
[    4.343997] si5341 7-0036: Chip: 5341 Grade: 1 Rev: 1
[    4.381433] i2c i2c-1: Added multiplexed i2c bus 7
[    4.389063] si570 8-005d: registered, current frequency 300000000 Hz
[    4.395452] i2c i2c-1: Added multiplexed i2c bus 8
[    4.400375] i2c i2c-1: Added multiplexed i2c bus 9
[    4.405422] si5324 10-0069: si5328 probed
[    4.470861] si5324 10-0069: si5328 probe successful
[    4.475766] i2c i2c-1: Added multiplexed i2c bus 10
[    4.481861] i2c i2c-1: Added multiplexed i2c bus 11
[    4.486866] i2c i2c-1: Added multiplexed i2c bus 12
[    4.491866] i2c i2c-1: Added multiplexed i2c bus 13
[    4.496744] pca954x 1-0074: registered 8 multiplexed busses for I2C switch pca9548
[    4.504755] i2c i2c-1: Added multiplexed i2c bus 14
[    4.509770] i2c i2c-1: Added multiplexed i2c bus 15
[    4.514772] i2c i2c-1: Added multiplexed i2c bus 16
[    4.520244] i2c i2c-1: Added multiplexed i2c bus 17
[    4.525255] i2c i2c-1: Added multiplexed i2c bus 18
[    4.530259] i2c i2c-1: Added multiplexed i2c bus 19
[    4.535387] at24 20-0050: supply vcc not found, using dummy regulator
[    4.569695] i2c i2c-1: Added multiplexed i2c bus 20
[    4.574821] at24 21-0050: supply vcc not found, using dummy regulator
[    4.581592] at24 21-0050: 256 byte 24c02 EEPROM, writable, 1 bytes/write
[    4.588330] i2c i2c-1: Added multiplexed i2c bus 21
[    4.593207] pca954x 1-0075: registered 8 multiplexed busses for I2C switch pca9548
[    4.600797] cdns-i2c ff030000.i2c: 400 kHz mmio ff030000 irq 40
```

Doing `ethtool -m eth2` then, to dump the EEPROM of the not plugged in module (eth2 == ZCU106 SFP1) then yields:

```
root@petalinux:~# ethtool -m eth2
Cannot get module EEPROM information: No such device or address
```

Which seems to be a reasonable message, since the device (== I2C slave == EEPROM) simply is not there.

When plugging the SFP module in, at runtime, successful dumping can be performed. Also, unplugging again after that and re-plugging yields the same result. This is also true for the other SFP module (in ZCU106 SFP0), which was there during boot up.

Then we quickly checked the situation for `fpga_pcie` design and found similar behavior. Again the second module (SFP1) is missing during boot in the following example:

```
[  100.489127] mqnic 0000:06:00.0: IF offset: 0x00000000
[  100.489128] mqnic 0000:06:00.0: IF count: 2
[  100.489129] mqnic 0000:06:00.0: IF stride: 0x00800000
[  100.489129] mqnic 0000:06:00.0: IF CSR offset: 0x00040000
[  100.560662] i2c i2c-12: Added multiplexed i2c bus 13
[  100.560722] i2c i2c-12: Added multiplexed i2c bus 14
[  100.560764] i2c i2c-12: Added multiplexed i2c bus 15
[  100.560802] i2c i2c-12: Added multiplexed i2c bus 16
[  100.560843] i2c i2c-12: Added multiplexed i2c bus 17
[  100.560883] i2c i2c-12: Added multiplexed i2c bus 18
[  100.560923] i2c i2c-12: Added multiplexed i2c bus 19
[  100.560961] i2c i2c-12: Added multiplexed i2c bus 20
[  100.560963] pca954x 12-0074: registered 8 multiplexed busses for I2C switch pca9548
[  100.561843] at24 13-0054: 1024 byte 24c08 EEPROM, writable, 1 bytes/write
[  100.562201] i2c i2c-12: Added multiplexed i2c bus 21
[  100.562267] i2c i2c-12: Added multiplexed i2c bus 22
[  100.562343] i2c i2c-12: Added multiplexed i2c bus 23
[  100.562453] i2c i2c-12: Added multiplexed i2c bus 24
[  100.562698] i2c i2c-12: Added multiplexed i2c bus 25
[  100.564473] i2c i2c-12: Added multiplexed i2c bus 26
[  100.564555] i2c i2c-12: Added multiplexed i2c bus 27
[  100.564624] i2c i2c-12: Added multiplexed i2c bus 28
[  100.564629] pca954x 12-0075: registered 8 multiplexed busses for I2C switch pca9548
[  100.565507] at24 28-0050: 256 byte 24c02 EEPROM, writable, 1 bytes/write
[  100.621919] mqnic 0000:06:00.0: registered PHC (index 2)
[  100.621921] mqnic 0000:06:00.0: Creating interface 0
```

So both I2C slave instances, for both SFP module EEPROMs are successfully created, even if the second module is actually not plugged in.

The only difference to the `fpga_zynqmp` case is the error message when trying to dump a missing module:

```
$ sudo ethtool -m ens2d1
Cannot get module EEPROM information: Input/output error
```

Here `ens2d1` is the netdev for the second SFP slot (ZCU106 SFP1). The difference could be originated from the fact that 2 different I2C masters are in the game here. For the `fpga_zynqmp` case it is the PS's hard-ip I2C master. And for the `fpga_pcie` it is the bitbang master from within mqnic, right?

**Comment by joft-mle** [comment]
> > From looking at the build instructions, I'm wondering if something can be simplified a abit:
> > ```
> > cd ps/petalinux/
> > make HDF=../../fpga/fpga.xsa gethdf
> > make
> > make package-boot
> > ```
> >   
> > Main thing I think is it would be nice to have the default value of HDF specified somewhere so it doesn't need to be specified manually when building. I can potentially see the point of not running gethdf on every build, but would it make sense to do that automatically on a clean build when running `make`?
> 
> Yes, simplification is indeed possible here; I'll come up with a conveniences make target via psmake's local.mk feature.

As can be seen in the updated [mle/zcu106-zynqmp](https://github.com/missinglinkelectronics/corundum/tree/mle/zcu106-zynqmp-axi) branch, I added another commit, which adds a shortcut target called `build-boot`, which combines the 3 `make` steps. And the HDF variable is defaulting to the `.xsa` file in the `fpga/` folder now.

Note that with `psmake`, the `make gethdf` and `make` (or `make build`, which is the default target), can be combined into one call. This way the `.xsa` file is imported into the PetaLinux project, if it has changed, only. The `gethdf` target is actually a way to force importing independent of changes.

**Comment by joft-mle** [comment]
> Hmm, that's interesting. I wonder if they added the explicit test of the EEPROM in a more recent kernel version or something. The thing is the I2C client is always created, but the EEPROM driver does not get attached to that I2C client unless the module is plugged in. As the smbus APIs that the driver uses to access the module EEPROMs only need the I2C client, they will work either way. But you don't get a sysfs entry for the eeprom itself (i.e. /sys/..../eeprom) so you can't access the eeprom directly with xxd or dd or whatever. But, it's nice to know that the device tree behaves similarly and will at least create the I2C clients.

Ok, yes. We did not check for the `eeprom/` node in sysfs. However I would be surprised, if they were not there, otherwise the kernel message during boot would be kind misleading? I would then expect to see a eeprom driver `probe()` error message instead. We'll check again ...

The kernel version for our test were: v5.10 for `fpga_zynqmp`. That's what PetaLinux v2021.1 uses. And v5.4 / Ubuntu 18.04 for the `fpga_pcie` case.

**Comment by joft-mle** [comment]
Just for completeness, for anyone reading this: The [mle/zcu106-zynqmp-axi](https://github.com/missinglinkelectronics/corundum/tree/mle/zcu106-zynqmp-axi) branch has been rebase'ed on top of yesterday's Corundum [master](https://github.com/corundum/corundum/commit/b7aa4f77d78a1ad3876860df961ca5ed85e9fd72) branch.

**Comment by alexforencich** [comment]
I haven't seen error messages in dmesg, it silently fails to attach.  But the client is still created.  From looking at the log you posted, it looks like only 1 of the 2 modules is actually registered:

    [    4.535387] at24 20-0050: supply vcc not found, using dummy regulator
    [    4.569695] i2c i2c-1: Added multiplexed i2c bus 20
    [    4.574821] at24 21-0050: supply vcc not found, using dummy regulator
    [    4.581592] at24 21-0050: 256 byte 24c02 EEPROM, writable, 1 bytes/write
    [    4.588330] i2c i2c-1: Added multiplexed i2c bus 21

It looks like the at24 driver for device 20-0050 says something about vcc, but then bails out and does not print anything about the EEPROM, while the at24 driver for 21-0050 does complete probing and attach properly.

**Comment by joft-mle** [comment]
> I haven't seen error messages in dmesg, it silently fails to attach. But the client is still created. From looking at the log you posted, it looks like only 1 of the 2 modules is actually registered:
> 
> ```
> [    4.535387] at24 20-0050: supply vcc not found, using dummy regulator
> [    4.569695] i2c i2c-1: Added multiplexed i2c bus 20
> [    4.574821] at24 21-0050: supply vcc not found, using dummy regulator
> [    4.581592] at24 21-0050: 256 byte 24c02 EEPROM, writable, 1 bytes/write
> [    4.588330] i2c i2c-1: Added multiplexed i2c bus 21
> ```
> 
> It looks like the at24 driver for device 20-0050 says something about vcc, but then bails out and does not print anything about the EEPROM, while the at24 driver for 21-0050 does complete probing and attach properly.



> I haven't seen error messages in dmesg, it silently fails to attach. But the client is still created. From looking at the log you posted, it looks like only 1 of the 2 modules is actually registered:
> 
> ```
> [    4.535387] at24 20-0050: supply vcc not found, using dummy regulator
> [    4.569695] i2c i2c-1: Added multiplexed i2c bus 20
> [    4.574821] at24 21-0050: supply vcc not found, using dummy regulator
> [    4.581592] at24 21-0050: 256 byte 24c02 EEPROM, writable, 1 bytes/write
> [    4.588330] i2c i2c-1: Added multiplexed i2c bus 21
> ```
> 
> It looks like the at24 driver for device 20-0050 says something about vcc, but then bails out and does not print anything about the EEPROM, while the at24 driver for 21-0050 does complete probing and attach properly.
> 
> And the PCIe one shows the same, only one EEPROM is registered, even though there are two ports. Well, two EEPROMs are registered, but the other one is a larger 24c08 that sits on the PCB.

You are right, I mis-read, scratch my comment.

**Comment by joft-mle** [comment]
> > Hmm, that's interesting. I wonder if they added the explicit test of the EEPROM in a more recent kernel version or something. The thing is the I2C client is always created, but the EEPROM driver does not get attached to that I2C client unless the module is plugged in. As the smbus APIs that the driver uses to access the module EEPROMs only need the I2C client, they will work either way. But you don't get a sysfs entry for the eeprom itself (i.e. /sys/..../eeprom) so you can't access the eeprom directly with xxd or dd or whatever. But, it's nice to know that the device tree behaves similarly and will at least create the I2C clients.
> 
> Ok, yes. We did not check for the `eeprom/` node in sysfs. ~~However I would be surprised, if they were not there, otherwise the kernel message during boot would be kind misleading? I would then expect to see a eeprom driver `probe()` error message instead.~~ We'll check again ...
> 
> The kernel version for our test were: v5.10 for `fpga_zynqmp`. That's what PetaLinux v2021.1 uses. And v5.4 / Ubuntu 18.04 for the `fpga_pcie` case.

**Comment by joft-mle** [comment]
> No worries, it's really a very strange issue. You would think that explicitly creating the instance would reliably result in it actually being created, but nope, in this case it's a totally silent failure. Unfortunately, whoever wrote that driver didn't realize hot plugging was a thing, and there isn't even a provision for "yes, please create this even if you can't poke at it right now".

So, I guess, for the `fpga_zynqmp`, we have to come up with a proper solution for that in the future. For the PCIe cases, this will all be handled by the mqnic itself (RISC V) in the future, right? But, when something else, here the ZynqMP PS is managing I2C for SFP EEPROMs, we need to dynamically (de/re-)attach the eeprom driver, most likely taking some "module inserted/removed" signal as a trigger.

(Sorry, accidentally closed the PR. I hit the wrong button. I'm lucky that there is a re-open button, too ;-) )

**Comment by alexforencich** [comment]
The buttons are right next to each other, it's easy hit the wrong one...

Anyway, I'm not sure what the proper solution should be.  I think so long as the mqnic driver doesn't actually use the eeprom driver, it could be good enough as is.  Right now, I use smbus APIs that only require the I2C client to be registered, they don't need any particular driver to be attached.

The other funny thing is that the EEPROM presence is only checked during probe.  If you pull the module afterwards, the EEPROM driver stays attached, and I think accesses to the sysfs entries will return IO errors until the module is reinserted.

**Comment by vamposdecampos** [comment]
There should be a sysfs entry for the driver, such as `/sys/bus/i2c/drivers/at24`; one could write to its `bind` entry to attach the eeprom driver after-the-fact.  Perhaps

    echo 20-0050 > /sys/bus/i2c/drivers/at24/bind

**Comment by alexforencich** [comment]
So, we're going to need to figure out a different way of doing the block diagrams.  I don't think exporting them from Vivado is going to work as if you do that they're locked to one specific version of Vivado.  For instance, I cannot build this code on 2021.2 without running the tcl in 2021.1 then opening the block diagram in 2021.2 and re-exporting the TCL.

**Comment by alexforencich** [comment]
After building the FPGA image with vivado 2021.1, I tried to build the kernel, and it failed with:

    Makefile:34: *** PETALINUX_VER is unset. This Makefile must be invoked from within a PetaLinux environment.  Stop.

I'm assuming something else needs to be done to set up the petalinux environment, which is not mentioned in the readme?

**Comment by joft-mle** [comment]
> After building the FPGA image with vivado 2021.1, I tried to build the kernel, and it failed with:
> 
> ```
> Makefile:34: *** PETALINUX_VER is unset. This Makefile must be invoked from within a PetaLinux environment.  Stop.
> ```
> 
> I'm assuming something else needs to be done to set up the petalinux environment, which is not mentioned in the readme?

No and yes ;-) . As briefly noted in the `README.md`:

`Ensure that the Xilinx PetaLinux toolchain components are in PATH.`

This typically means to source the `settings.sh` file within one's PetaLinux installation. It is the same concept in PetaLinux as in Vivado, except that the file to be sourced is called `settings64.sh` in Vivado. However, in the end, this really depends on "how" exactly the toolchain is "installed" on a particular system. Our assumption is, that the user has to known how to enter the required environments. Perhaps we need to come up with a better instruction/sentence?

**Comment by joft-mle** [comment]
> So, we're going to need to figure out a different way of doing the block diagrams. I don't think exporting them from Vivado is going to work as the exported TCL seems to be locked one specific version of Vivado. For instance, I cannot build this code on 2021.2 without running the tcl in 2021.1 then opening the block diagram in 2021.2 and re-exporting the TCL.
> 
> ```
> ERROR: [BD::TCL 103-2041] This script was generated using Vivado <2021.1> and is being run in <2021.2> of Vivado. Please run the script in Vivado <2021.1> then open the design in Vivado <2021.2>. Upgrade the design by running "Tools => Report => Report IP Status...", then run write_bd_tcl to create an updated script.
> ```

Yes, unfortunately this is expected. I don't know, if it is possible to come up with a generic solution - never tried it.

> 
> TBH, if this is the case, then it's almost better to commit the actual block diagram as you don't need the old version of Vivado to run the TCL script.

Yes, committing the block diagram additionally can be a workaround. However, I'd always keep the TCL for reference, since that is, what at least I would consider as the "source" (unfortunately version dependent). The block diagram is more like a "binary" in my perception.

> We may need to do some tests, but it's possible that the most reliable way to do this would be to manually write TCL to create the block diagram instead of drawing the block diagram in Vivado and exporting the TCL, similar to what I do with the CMS IP on the Alveo boards.

I'd suggest to take the exported TCL from Vivado and try to manually "make it generic". And keep the formatting, in order to be able to later easily spot a diff, when comparing with what Vivado exports, in case of debugging etc.

**Comment by alexforencich** [comment]
I got petalinux installed and on the path, but the build fails with:

```
| In file included from /usr/include/signal.h:328,
|                  from ./signal.h:52,
|                  from ../../m4-1.4.18/lib/c-stack.c:49:
| ../../m4-1.4.18/lib/c-stack.c:55:26: error: missing binary operator before token "("
|    55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
|       |                          ^~~~~~~~
```

**Comment by alexforencich** [comment]
And yes, I am thinking the readmes should probably be reworked to be a bit more explicit.  Although, the getting started guide in the main docs does have a lot more detail, so perhaps we just need to add a section there about building for MPSoC devices.  And then point all of the readmes at the main documentation.

**Comment by alexforencich** [comment]
I'm wondering, what is the "best" method to set the interface MAC addresses?  I don't really like adding a whole pile of parameters so the driver can extract the MAC out of an EEPROM.  I mean, I guess it works, but it seems like the MAC address could potentially come from quite a few different sources, in addition to an I2C EEPROM.  On an SoC, you have the device tree which defines all sorts of stuff.  Seems like putting the MACs directly in the device tree is one relatively common solution, see https://support.xilinx.com/s/article/53476?language=en_US .  There is a Trenz board that also seems to be able to read the GEM MAC out of an EEPROM, see https://forum.trenz-electronic.de/index.php?topic=1093.0.  It seems like it may even be possible to set up the device tree to reference a MAC in an EEPROM, see: https://gist.github.com/znuh/bfea1690291795c421f64a6b4b1904c0 .

**Comment by alexforencich** [comment]
Also, I did finally get the design to build and boot on my ZCU106.  First, it doesn't build under Arch, that's apparently too new and is triggering some bugs in m4 and possibly some other components, so I had to build on one of my dev machines that I booted into Ubuntu.  Second, I had to figure out how to add linuxptp and change the kernel config to enable PTP clock support.  But, with that done, the design runs, I can get 4-5 Gbps TX and 2-3 Gbps RX with iperf, and PTP time sync also works.

**Comment by joft-mle** [comment]
> I'm wondering, what is the "best" method to set the interface MAC addresses? I don't really like adding a whole pile of parameters so the driver can extract the MAC out of an EEPROM. I mean, I guess it works, but it seems like the MAC address could potentially come from quite a few different sources, in addition to an I2C EEPROM. On an SoC, you have the device tree which defines all sorts of stuff. Seems like putting the MACs directly in the device tree is one relatively common solution, see https://support.xilinx.com/s/article/53476?language=en_US .

Yes, reading from the device tree directly is another possibility. IMHO it only makes sense, when the boot loader is actually inserting it into the otherwise static device tree blob. So the boot loader needs to be aware of that and essentially read the MAC from somewhere (EEPROM) and place it into the device tree. Setting a MAC address at build time (when the static device tree is built), essentially inhibits the use of a built image file on multiple boards.

> There is a Trenz board that also seems to be able to read the GEM MAC out of an EEPROM, see https://forum.trenz-electronic.de/index.php?topic=1093.0.

Yes, the driver for the PS GEM does that generally I think - indirectly. See above, via the boot loader placing it in the DT after reading from EEPROM ... if I'm not mistaken.

> It seems like it may even be possible to set up the device tree to reference a MAC in an EEPROM, see: https://gist.github.com/znuh/bfea1690291795c421f64a6b4b1904c0 .

That's very interesting, thanks. I missed that. So I agree, introducing a bunch of new properties does not make sense then. At least the basics are there already (except for setting the local-bit, I think). I guess, we need to come up with modifications to the PR here to not establish any non-standard properties.

**Comment by alexforencich** [comment]
I suppose another option for handling the MAC address could be to have the device tree provide either a base MAC or a MAC list, and then have some device tree options for how to derive additional MACs from that base MAC.  I think this would end up being a more flexible solution for SoC devices that use the device tree.  TBH, the MAC address handling in general could probably use some work.

The thing to keep in mind is that for PCIe devices, the host has to do everything through the PCIe link (and therefore through Corundum itself), including reading MAC addresses, accessing optical modules, etc.  On a SoC, it's not necessarily going to be the case that everything has to go through Corundum.  You guys have already updated the driver to support using the SoC I2C interfaces for interfacing with the optical modules.  We may need to do something similar for the module control pins, in case they're connected to I2C port expanders or something.  Similar thing with the MAC addresses - the driver just needs to get the MAC address from somewhere, and it seems like the device tree might be the more general way of doing that.

**Comment by alexforencich** [comment]
Looks like there have been some other discussions about extending MAC address handling:

https://patchwork.ozlabs.org/project/devicetree-bindings/patch/20200920095724.8251-4-ansuelsmth@gmail.com/#2539018
https://lore.kernel.org/netdev/20190510181631.GE11588@lunn.ch/t/
https://patchwork.ozlabs.org/project/devicetree-bindings/patch/20190511144444.GU81826@meh.true.cz/

Not sure if any of these went anywhere, from looking at https://elixir.bootlin.com/linux/latest/source/net/core/of_net.c#L124, seems like none of this has been merged yet.

**Comment by alexforencich** [comment]
Well, I guess we could always pull in one of those MAC address increment patches, even if it's not in the mainline.  We are building the kernel from source after all.

**Comment by alexforencich** [comment]
Anyway, this is looking really good and I would like to get it merged soon.  If we can back out [2ac0f10](https://github.com/corundum/corundum/pull/98/commits/2ac0f10c219b0896c1c6f531dfcf283a5940e333) and use the MAC from the device tree directly, using nvmem to read it from the EEPROM, possibly with some post-processing via additional device tree parameters (increment, set local bit, etc.), then I think we should be good to go.

**Comment by joft-mle** [comment]
Hi @alexforencich ,

I've just updated our [mle/zcu106-zynqmp-axi](https://github.com/missinglinkelectronics/corundum/tree/mle/zcu106-zynqmp-axi) branch once more, including the following changes:

- Provide a dedicated function to determine the MAC address, using the generic kernel function [`eth_platform_get_mac_address()`](https://lxr.missinglinkelectronics.com/linux/net/ethernet/eth.c#L507), which in turn uses `of_get_mac_address()` and thus makes use of device tree `mac-address` property or `nvmem-cells`.
- Modeled MAC address modification after [one of the links you provided](https://patchwork.ozlabs.org/project/devicetree-bindings/patch/20200920095724.8251-4-ansuelsmth@gmail.com/#2539018), including the custom "make it a local MAC address" switch.
- The rest of the old `mqnic_platform_of_get/put()` deals with getting hold of module EEPROMs, only, now, thus renamed (`mqnic_platform_module_eeprom_get/put()`).
- Stop using and/or modifying anything from `mqnic_board.c`; also since it will go away anyway.
- "Optimized" error path in `mqnic_platform_of_put()`, warning vs. error; also: no need to call `mqnic_platform_of_get/put()` in `mqnic_common_probe()` anymore
- Add a section in the documentation regarding PetaLinux Tools and its `settings.sh`.

I have yet to do a final quick sanity check - clean rebuild etc. ... Would be good if you had a look at it in the meantime ...

**Comment by alexforencich** [comment]
Dangit, I just spent far too long debugging this when it turns out the MAC was programmed wrong on my ZCU106:

    # hexdump -C /sys/bus/i2c/devices/6-0054/eeprom 
    00000000  39 32 31 37 33 39 34 38  31 39 34 38 2d 32 31 35  |921739481948-215|
    00000010  30 39 ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |09..............|
    00000020  01 02 03 04 05 06 ff ff  ff ff ff ff ff ff ff ff  |................|
    00000030  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
    *
    000000d0  5a 43 55 31 30 36 20 20  20 20 20 ff ff ff ff ff  |ZCU106     .....|
    000000e0  31 2e 30 ff ff ff ff ff  ff ff ff ff ff ff ff ff  |1.0.............|
    000000f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
    *
    00000400

With that fixed (slightly annoying to not have xxd in the image....), the result is:

    3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
        link/ether 00:0a:35:05:3a:a8 brd ff:ff:ff:ff:ff:ff
        inet6 fd1d:2f00:1b5a:0:20a:35ff:fe05:3aa8/64 scope global dynamic mngtmpaddr 
           valid_lft forever preferred_lft forever
        inet6 2603:8001:8e00:de:20a:35ff:fe05:3aa8/64 scope global dynamic mngtmpaddr 
           valid_lft 580717sec preferred_lft 580717sec
        inet6 fe80::20a:35ff:fe05:3aa8/64 scope link 
           valid_lft forever preferred_lft forever
    4: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
        link/ether 02:0a:35:05:3a:a9 brd ff:ff:ff:ff:ff:ff
    5: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
        link/ether 02:0a:35:05:3a:aa brd ff:ff:ff:ff:ff:ff

So, I think we are good to go with this.  Excellent!

**Comment by alexforencich** [comment]
The ZCU106 design along with the driver modifications have now been pulled in to this repo.  See https://github.com/corundum/corundum/tree/master/fpga/mqnic/ZCU106/fpga_zynqmp for the ZCU106 example design.

Thank you very much to the folks at Missing Link Electronics for making this happen!

**Pull request merged**
